const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const S={view:"home",filter:"available",q:"",books:[],people:[],tab:"barcode",draft:null,active:null};
const DB="hearth-amber-v1";
const uid=()=>crypto.randomUUID?crypto.randomUUID():"id-"+Date.now();
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s||"").replace(/[&<>"]/g,c=>({"&":"&","<":"<",">":">","\"":"""}[c]));
function idb(mode,store,fn){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;["books","people"].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:"id"});});};r.onsuccess=()=>{const tx=r.result.transaction(store,mode);fn(tx.objectStore(store),res);tx.onerror=()=>rej(tx.error);};r.onerror=()=>rej(r.error);});}
const all=st=>idb("readonly",st,(s,res)=>{const q=s.getAll();q.onsuccess=()=>res(q.result||[]);});
const put=(st,v)=>idb("readwrite",st,(s,res)=>{s.put(v);s.transaction.oncomplete=()=>res();});
const del=(st,id)=>idb("readwrite",st,(s,res)=>{s.delete(id);s.transaction.oncomplete=()=>res();});
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200);}
function cover(b){return b.coverDataUrl||b.coverUrl||(b.isbn?`https://covers.openlibrary.org/b/isbn/${b.isbn}-M.jpg`:"");}
function isbn(s){return String(s||"").replace(/[^0-9Xx]/g,"").toUpperCase();}
function okIsbn(s){const n=isbn(s);return n.length===10||n.length===13;}
function label(s){return {owned:"On shelf",reading:"Reading",read:"Read",loaned:"Loaned",wishlist:"Buy / want"}[s]||s;}
function blank(){return {id:uid(),title:"",authors:[],isbn:"",coverUrl:"",coverDataUrl:"",year:"",vibe:"",notes:"",status:"owned",location:"Amber's place",loanedTo:"",loanedAt:"",dateRead:"",dateAdded:today(),source:"manual",updatedAt:Date.now()};}
async function load(){S.books=await all("books");S.people=await all("people");if(!S.people.length){S.people=[{id:uid(),name:"Brian",favorite:true},{id:uid(),name:"Belle",favorite:true}];for(const p of S.people)await put("people",p);}}
async function save(b){b.updatedAt=Date.now();await put("books",b);const i=S.books.findIndex(x=>x.id===b.id);if(i>=0)S.books[i]=b;else S.books.unshift(b);}
function stats(){const now=new Date(),w=new Date(now);w.setDate(now.getDate()-now.getDay());w.setHours(0,0,0,0);const m=new Date(now.getFullYear(),now.getMonth(),1),y=new Date(now.getFullYear(),0,1);const fin=S.books.filter(b=>b.dateRead);const n=d=>fin.filter(b=>new Date(b.dateRead)>=d).length;return {week:n(w),month:n(m),year:n(y),owned:S.books.filter(b=>b.status!=="wishlist").length,loaned:S.books.filter(b=>b.status==="loaned").length};}
function listed(){let L=S.books.slice();if(S.q){const q=S.q.toLowerCase();L=L.filter(b=>[b.title,(b.authors||[]).join(" "),b.isbn,b.loanedTo,b.vibe].join(" ").toLowerCase().includes(q));}if(S.filter==="available")L=L.filter(b=>b.status!=="loaned"&&b.status!=="wishlist");else if(S.filter!=="all")L=L.filter(b=>b.status===S.filter);return L.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));}
function score(b,mood){const bag=mood.toLowerCase().split(/\W+/).filter(w=>w.length>2);const extra={magical:"fantasy magic witch wizard fairy myth dragon spell",cozy:"cozy comfort warm cottage tea",dark:"dark grim horror gothic",funny:"funny humor comedy witty",space:"space science future ai"};let words=[...bag];bag.forEach(w=>{if(extra[w])words.push(...extra[w].split(" "));});const hay=[b.title,(b.authors||[]).join(" "),b.vibe,b.notes,(b.subjects||[]).join(" ")].join(" ").toLowerCase();let s=0;words.forEach(w=>{if(hay.includes(w))s+=2;});if(b.status==="loaned")s-=8;return s;}
function card(b){const c=cover(b);return `<button class="book-card" data-open="${b.id}"><div class="cover">${c?`<img src="${c}" alt="" onerror="this.remove()">`:`<div class="fallback">${esc(b.title)}</div>`}${b.status==="loaned"?`<span class="badge">${esc(b.loanedTo||"out")}</span>`:b.status!=="owned"?`<span class="badge">${label(b.status)}</span>`:""}</div><h3>${esc(b.title)}</h3><p>${esc((b.authors||[])[0]||"")}</p></button>`;}
function home(){const st=stats(),books=listed();const ios=/iPhone|iPad|iPod/.test(navigator.userAgent)&&!(window.navigator.standalone||matchMedia("(display-mode: standalone)").matches);$("#home").innerHTML=`${ios?`<section class="mood-card"><h2>Put this on the Home Screen</h2><p class="hint">Safari → Share → Add to Home Screen → Add.</p></section>`:""}<section class="mood-card"><h2>Tonight’s vibe</h2><p class="hint">Shelves first. Buy list only if nothing fits.</p><div class="mood-row"><input id="moodInput" type="text" placeholder="something magical…"><button class="pill gold" id="moodGo">Find</button></div></section><section class="stats-row"><div class="stat"><b>${st.week}</b><span>this week</span></div><div class="stat"><b>${st.month}</b><span>this month</span></div><div class="stat"><b>${st.year}</b><span>this year</span></div></section><div class="filters">${[["available","On shelf"],["all","All"],["reading","Reading"],["loaned","Loaned"],["read","Finished"],["wishlist","Want"]].map(([id,l])=>`<button class="chip ${S.filter===id?"on":""}" data-f="${id}">${l}</button>`).join("")}</div>${books.length?`<div class="grid">${books.map(card).join("")}</div>`:`<div class="empty"><h3>The hearth is empty.</h3><p>Add a book by barcode, cover, title, or ISBN.</p></div>`}`;$("#moodGo").onclick=runMood;$$("[data-f]").forEach(c=>c.onclick=()=>{S.filter=c.dataset.f;draw();});bind();}
function loans(){const L=S.books.filter(b=>b.status==="loaned");$("#loans").innerHTML=`<div class="mood-card"><h2>Out of the house</h2><p class="hint">${L.length} loaned.</p></div>${L.length?`<div class="list">${L.map(b=>`<button class="row" data-open="${b.id}"><div class="mini">${cover(b)?`<img src="${cover(b)}">`:""}</div><div><h3>${esc(b.title)}</h3><p>with ${esc(b.loanedTo||"someone")}</p></div></button>`).join("")}</div>`:`<div class="empty"><h3>Nothing is out.</h3></div>`}`;bind();}
function statsView(){const st=stats();$("#statsView").innerHTML=`<div class="stats-row"><div class="stat"><b>${st.owned}</b><span>in inventory</span></div><div class="stat"><b>${st.loaned}</b><span>loaned</span></div><div class="stat"><b>${st.year}</b><span>finished ${new Date().getFullYear()}</span></div></div>`;}
function people(){$("#peopleView").innerHTML=`<div class="mood-card"><h2>People</h2><div class="field"><label>New person</label><div class="mood-row"><input id="newPerson" type="text"><button class="pill gold" id="addP">Add</button></div></div><div class="people" style="margin-top:8px">${S.people.map(p=>`<button class="person ${p.favorite?"fav":""}" data-pid="${p.id}">${esc(p.name)}${p.favorite?" ★":""}</button>`).join("")}</div></div>`;$("#addP").onclick=async()=>{const n=$("#newPerson").value.trim();if(!n)return;const p={id:uid(),name:n,favorite:true};S.people.push(p);await put("people",p);draw();};$$("[data-pid]").forEach(b=>b.onclick=async()=>{const p=S.people.find(x=>x.id===b.dataset.pid);p.favorite=!p.favorite;await put("people",p);draw();});}
function settings(){$("#settingsView").innerHTML=`<div class="mood-card"><h2>This copy</h2><p class="hint">Library lives on this device. Export often.</p></div><div class="btn-row"><button class="btn ghost" id="ex">Export JSON</button><button class="btn ghost file-btn">Import JSON<input id="im" type="file" accept="application/json"></button></div><button class="btn ghost" id="demo" style="margin-top:8px">Load 3 sample books</button>`;$("#ex").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({books:S.books,people:S.people},null,2)],{type:"application/json"}));a.download="hearth-"+today()+".json";a.click();};$("#im").onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());for(const b of d.books||[])await put("books",b);for(const p of d.people||[])await put("people",p);await load();draw();toast("Imported");}catch{toast("Import failed");}};$("#demo").onclick=loadDemo;}
function viewId(v){return {home:"home",loans:"loans",stats:"statsView",people:"peopleView",settings:"settingsView"}[v];}
function draw(){$$(".nav button").forEach(b=>b.classList.toggle("on",b.dataset.view===S.view));$$(".screen").forEach(s=>s.classList.toggle("hidden",s.id!==viewId(S.view)));if(S.view==="home")home();if(S.view==="loans")loans();if(S.view==="stats")statsView();if(S.view==="people")people();if(S.view==="settings")settings();}
function bind(){$$("[data-open]").forEach(el=>el.onclick=()=>openBook(el.dataset.open));}
function openSheet(){$("#sheet").classList.add("open");}
function closeSheet(){$("#sheet").classList.remove("open");}
function addUI(){S.draft=blank();$("#sheetBody").innerHTML=`<div class="handle"></div><div class="sheet-head"><h2>Add a book</h2><button class="icon-btn" id="x">✕</button></div><div class="tabs" id="tabs"><button class="tab on" data-t="barcode">Barcode</button><button class="tab" data-t="cover">Cover</button><button class="tab" data-t="search">Title</button><button class="tab" data-t="isbn">ISBN</button><button class="tab" data-t="manual">Manual</button></div><div class="pane" data-p="barcode"><p class="hint">Photograph the ISBN barcode on the back.</p><button class="btn file-btn">Photograph barcode<input id="bf" type="file" accept="image/*" capture="environment"></button><div id="bst" class="hint"></div></div><div class="pane hidden" data-p="cover"><p class="hint">Front cover photo. Barcode in the frame will be read.</p><button class="btn file-btn">Photograph cover<input id="cf" type="file" accept="image/*" capture="environment"></button></div><div class="pane hidden" data-p="search"><div class="field"><label>Title</label><input id="qt"></div><div class="field"><label>Author</label><input id="qa"></div><button class="btn" id="sb">Search catalogs</button></div><div class="pane hidden" data-p="isbn"><div class="field"><label>ISBN</label><input id="qi" inputmode="numeric"></div><button class="btn" id="ib">Look up</button></div><div class="pane hidden" data-p="manual"><div class="field"><label>Title</label><input id="mt"></div><div class="field"><label>Author</label><input id="ma"></div><div class="field"><label>ISBN</label><input id="mi"></div><div class="field"><label>Vibe tags</label><input id="mv" placeholder="magical, quiet"></div><button class="btn" id="sm">Save to shelf</button></div><div id="hits" class="results"></div>`;openSheet();$("#x").onclick=closeSheet;$$("#tabs .tab").forEach(t=>t.onclick=()=>{$$("#tabs .tab").forEach(x=>x.classList.toggle("on",x===t));$$(".pane").forEach(p=>p.classList.toggle("hidden",p.dataset.p!==t.dataset.t));});$("#bf").onchange=()=>fromImg($("#bf").files[0],false);$("#cf").onchange=()=>fromImg($("#cf").files[0],true);$("#sb").onclick=()=>search($("#qt").value,$("#qa").value);$("#ib").onclick=()=>byIsbn($("#qi").value);$("#sm").onclick=async()=>{const b=S.draft;b.title=$("#mt").value.trim();b.authors=$("#ma").value.split(",").map(s=>s.trim()).filter(Boolean);b.isbn=isbn($("#mi").value);b.vibe=$("#mv").value.trim();if(!b.title)return toast("Needs a title");await commit(b);};}
async function fromImg(file,keep){if(!file)return;if(keep){S.draft.coverDataUrl=await new Promise(r=>{const f=new FileReader();f.onload=()=>r(f.result);f.readAsDataURL(file);});}try{if(window.Html5Qrcode){const id="t"+Date.now(),d=document.createElement("div");d.id=id;d.style.display="none";document.body.appendChild(d);try{const code=isbn(await new Html5Qrcode(id).scanFile(file,true));d.remove();if(okIsbn(code)){toast("Barcode "+code);return byIsbn(code);}}catch{d.remove();}}}catch(e){}toast("No barcode — search by title");}
async function byIsbn(raw){const code=isbn(raw);if(!okIsbn(code))return toast("Not an ISBN");toast("Looking up "+code);let b=null;const g=await get(`https://www.googleapis.com/books/v1/volumes?q=isbn:${code}`);if(g&&g.items&&g.items[0])b=vol(g.items[0],code);if(!b){const ol=await get(`https://openlibrary.org/api/books?bibkeys=ISBN:${code}&format=json&jscmd=data`);const rec=ol&&ol["ISBN:"+code];if(rec)b=Object.assign(blank(),{title:rec.title||"",authors:(rec.authors||[]).map(a=>a.name),isbn:code,year:(rec.publish_date||"").slice(-4),coverUrl:(rec.cover&&(rec.cover.large||rec.cover.medium))||`https://covers.openlibrary.org/b/isbn/${code}-L.jpg`,subjects:(rec.subjects||[]).slice(0,8).map(s=>s.name||s)});}if(!b){toast("Not in catalogs. Use manual.");S.draft.isbn=code;return;}if(S.draft&&S.draft.coverDataUrl)b.coverDataUrl=S.draft.coverDataUrl;show([b]);}
async function search(title,author){if(!title.trim()&&!author.trim())return toast("Title or author");let q="";if(title)q+=`intitle:${title}`;if(author)q+=(q?"+":"")+`inauthor:${author}`;const g=await get(`https://www.googleapis.com/books/v1/volumes?q=${encodeURIComponent(q)}&maxResults=10`);const list=(g&&g.items||[]).map(it=>vol(it));if(!list.length)return toast("No hits. Use manual.");show(list);}
function vol(item,hint){const i=item.volumeInfo||{},ids=i.industryIdentifiers||[];return Object.assign(blank(),{title:i.title||"Untitled",authors:i.authors||[],isbn:hint||(ids.find(x=>x.type==="ISBN_13")||ids.find(x=>x.type==="ISBN_10")||{}).identifier||"",year:(i.publishedDate||"").slice(0,4),subjects:i.categories||[],coverUrl:(i.imageLinks&&(i.imageLinks.thumbnail||i.imageLinks.smallThumbnail)||"").replace("http:","https:")});}
async function get(u){try{const r=await fetch(u);return r.ok?r.json():null;}catch{return null;}}
function show(list){const box=$("#hits");box._=list;box.innerHTML=list.slice(0,10).map((b,i)=>`<button class="result" data-i="${i}">${cover(b)?`<img src="${cover(b)}">`:`<div class="ph"></div>`}<div><h3>${esc(b.title)}</h3><p>${esc((b.authors||[]).join(", "))}</p></div><span class="chip">Add</span></button>`).join("");$$("[data-i]",box).forEach(btn=>btn.onclick=()=>commit(Object.assign(blank(),list[+btn.dataset.i],{id:uid(),coverDataUrl:S.draft&&S.draft.coverDataUrl})));}
async function commit(b){if(b.isbn&&S.books.find(x=>x.isbn===b.isbn)){toast("Already on the shelf");return;}await save(b);closeSheet();toast("Shelved: "+b.title);draw();}
function openBook(id){const b=S.books.find(x=>x.id===id);if(!b)return;S.active=id;const c=cover(b);const people=[...S.people.filter(p=>p.favorite),...S.people.filter(p=>!p.favorite)];$("#sheetBody").innerHTML=`<div class="handle"></div><div class="sheet-head"><h2>${esc(b.title)}</h2><button class="icon-btn" id="x">✕</button></div>${c?`<img class="cover-preview" src="${c}">`:""}<p class="hint">${esc((b.authors||[]).join(", "))}${b.isbn?" · "+b.isbn:""}</p><div class="field"><label>Status</label><select id="st">${["owned","reading","read","loaned","wishlist"].map(s=>`<option value="${s}" ${b.status===s?"selected":""}>${label(s)}</option>`).join("")}</select></div><div class="field"><label>Vibe tags</label><input id="vb" value="${esc(b.vibe)}"></div><div class="field"><label>Finished on</label><input id="rd" type="date" value="${esc(b.dateRead||"")}"></div><div class="field"><label>Loan to</label><select id="ln"><option value="">— not loaned —</option>${people.map(p=>`<option ${b.loanedTo===p.name?"selected":""}>${esc(p.name)}</option>`).join("")}</select></div><div class="field"><label>Or type a name</label><input id="ln2"></div><div class="field"><label>Notes</label><textarea id="nt">${esc(b.notes)}</textarea></div><button class="btn" id="sv">Save</button><div class="btn-row"><button class="btn ghost" id="fin">Mark finished today</button><button class="btn ghost" id="ret">Returned</button></div><button class="btn bad" id="rm">Remove</button>`;openSheet();$("#x").onclick=closeSheet;$("#sv").onclick=()=>persist();$("#fin").onclick=()=>persist("read");$("#ret").onclick=()=>persist("return");$("#rm").onclick=async()=>{S.books=S.books.filter(x=>x.id!==id);await del("books",id);closeSheet();draw();};}
async function persist(flag){const b=S.books.find(x=>x.id===S.active);if(!b)return;b.status=$("#st").value;b.vibe=$("#vb").value.trim();b.dateRead=$("#rd").value;b.notes=$("#nt").value.trim();const who=$("#ln2").value.trim()||$("#ln").value;if(flag==="read"){b.status="read";b.dateRead=today();b.loanedTo="";}else if(flag==="return"){b.status="owned";b.loanedTo="";}else if(who){b.status="loaned";b.loanedTo=who;b.loanedAt=b.loanedAt||today();if($("#ln2").value.trim()&&!S.people.some(p=>p.name.toLowerCase()===who.toLowerCase())){const p={id:uid(),name:who,favorite:false};S.people.push(p);await put("people",p);}}await save(b);closeSheet();toast("Updated");draw();}
function runMood(){const mood=$("#moodInput").value.trim();if(!mood)return toast("Give Ada a vibe");const ranked=S.books.map(b=>({b,s:score(b,mood)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s);const shelf=ranked.filter(x=>x.b.status!=="loaned"&&x.b.status!=="wishlist").slice(0,8);const buy=ranked.filter(x=>x.b.status==="wishlist").slice(0,6);$("#sheetBody").innerHTML=`<div class="handle"></div><div class="sheet-head"><h2>Tonight</h2><button class="icon-btn" id="x">✕</button></div><p class="ada">${shelf.length?`${shelf.length} already in hand for “${esc(mood)}”. Start there.`:`Nothing on the shelf is a clean hit for “${esc(mood)}”.`}</p><h3 style="margin:8px 0">From the shelves</h3>${shelf.length?`<div class="list">${shelf.map(({b})=>`<button class="row" data-open="${b.id}"><div class="mini">${cover(b)?`<img src="${cover(b)}">`:""}</div><div><h3>${esc(b.title)}</h3><p>${esc((b.authors||[])[0]||"")}</p></div></button>`).join("")}</div>`:`<p class="hint">Empty.</p>`}<h3 style="margin:16px 0 8px">Buy / want</h3>${buy.length?`<div class="list">${buy.map(({b})=>`<button class="row" data-open="${b.id}"><div class="mini"></div><div><h3>${esc(b.title)}</h3></div></button>`).join("")}</div>`:`<p class="hint">No wants tagged for that mood.</p>`}`;openSheet();$("#x").onclick=closeSheet;bind();}
async function loadDemo(){const samples=[{title:"Uprooted",authors:["Naomi Novik"],isbn:"9780804179041",vibe:"magical dark forest fairy tale",subjects:["Fantasy"]},{title:"Project Hail Mary",authors:["Andy Weir"],isbn:"9780593135204",vibe:"science lonely funny space",subjects:["Science fiction"]},{title:"Piranesi",authors:["Susanna Clarke"],isbn:"9781635575637",vibe:"magical quiet strange labyrinth",subjects:["Fantasy"]}];for(const s of samples){if(!S.books.some(b=>b.isbn===s.isbn)){const b=Object.assign(blank(),s);b.coverUrl=`https://covers.openlibrary.org/b/isbn/${s.isbn}-L.jpg`;await save(b);}}draw();toast("Samples loaded");}
async function boot(){await load();$$(".nav button").forEach(b=>b.onclick=()=>{S.view=b.dataset.view;draw();});$("#addBtn").onclick=addUI;$("#searchBox").addEventListener("input",e=>{S.q=e.target.value;if(S.view==="home")home();});$("#sheet").addEventListener("click",e=>{if(e.target.id==="sheet")closeSheet();});draw();}
document.addEventListener("DOMContentLoaded",boot);
